#array_width =
#attr_fn_like_width =
#chain_width =
edition = "2018"
fn_args_layout = "Tall"
#fn_call_width =
force_explicit_abi = true
hard_tabs = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = false
max_width = 130
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
#struct_lit_width =
#struct_variant_width =
tab_spaces = 3
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true

# unstable options
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = true
comment_width = 130
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
enum_discrim_align_threshold = 0
error_on_line_overflow = false
error_on_unformatted = false
fn_single_line = false
force_multiline_blocks = false
format_code_in_doc_comments = true
format_generated_files = false
format_macro_matchers = true
format_macro_bodies = true
format_strings = false
hex_literal_case = "Lower"
hide_parse_errors = false
#ignore =
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
license_template_path = ""
match_arm_blocks = true
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
report_fixme = "Never"
report_todo = "Never"
#required_version =
skip_children = false
single_line_if_else_max_width = 0
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Compressed"
unstable_features = false
version = "Two"
where_single_line = false
wrap_comments = true
