language: rust
sudo: false

addons:
  apt:
    packages:
      - curl
      - build-essential
      - wget
      - unzip
      - cmake
      - git
      - libgtk2.0-dev
      - pkg-config
      - libavcodec-dev
      - libavformat-dev
      - libswscale-dev
      - python-dev
      - python-numpy
      - libtbb2
      - libtbb-dev
      - libjpeg-dev
      - libpng-dev
      - libtiff-dev
      - libjasper-dev
      - libdc1394-22-dev
      - tree

env:
  global:
    - DOC=3.0.0
  matrix:
    - CV=3.0.0

before_script:
  - |
    if [ ! -e /tmp/opencv/opencv-$CV/release/unix-install ]
    then
      mkdir -p /tmp/opencv
      cd /tmp/opencv
      rm -rf opencv-$CV
      wget https://github.com/Itseez/opencv/archive/$CV.zip
      unzip -q $CV.zip
      cd opencv-$CV
      mkdir release install
      cd release
      cmake -D CMAKE_BUILD_TYPE=RELEASE -DBUILD_SHARED_LIBS=OFF -D CMAKE_INSTALL_PREFIX=/tmp/opencv/opencv-$CV/install -D WITH_FFMPEG=OFF ..
      make install
    fi
  - cd /home/travis/build/kali/opencv-rust
  - export PKG_CONFIG_PATH=/tmp/opencv/opencv-$CV/release/unix-install
  - pkg-config --cflags opencv
  - pkg-config --libs opencv
  - gcc --version

after_success:
  - echo $TRAVIS_RUST_VERSION
  - |
    if [ "$CV" = "$DOC" -a "$TRAVIS_RUST_VERSION" = "stable" ]
    then
      cargo doc
      curl https://raw.githubusercontent.com/kmcallister/travis-doc-upload/master/travis-doc-upload.sh | sh
    fi

#cache:
#  directories:
#    - /tmp/opencv

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
#  include:
#    - rust: stable
#      env: CV=2.4.10
